### ISSUE TITLE
Custom prefixes

### ISSUE THREAD

**Issue by Sodre177** [Intery/dpy-cmdClient#2]
Add support for custom prefixes via a method which returns the current valid prefixes given the client and the message.

**Comment by Sodre177** [comment]
Could probably use a decorator to set the prefix function.

**Comment by Intery** [comment]
# Implementation
Create a decorator method `current_prefixes` to `cmdClient` which accepts the client and the message.

Also allow the initial command parser to be overridden for more complex behaviour such as for custom commands, or for commands with no prefixes (e.g. using `?` as a shortcut for `<prefix>tag`).
